<?php

/*
 * DO NOT EDIT THIS FILE. USE INESTEAD FOLLOWING FILES:
 * 
 *   custom/custom.css - for frontend style sheet
 *   custom/custom.js  - for frontend JavaScript
 *   custom/custom.php - for backend PHP
*/


define('FL_CHILD_THEME_DIR', get_stylesheet_directory());
define('FL_CHILD_THEME_URL', get_stylesheet_directory_uri());

// Include `responsive-fonts.less`, which provides for responsive font sizes.
add_filter('fl_theme_compile_less_paths', function($paths) {
  $paths[] = FL_CHILD_THEME_DIR . '/responsive-fonts.less';
  return $paths;
});

// Add LESS variables used by `responsive-fonts.less`.
add_filter('fl_less_vars', function($vars) {

  // Use the gloabal break points of Beaver Bulider's Page Builder
  // as break points for responsive fonts.
  if (class_exists('FLBuilderModel')) {
    $global_settings = FLBuilderModel::get_global_settings();
    $vars['medium_breakpoint'] = $global_settings->medium_breakpoint . 'px';
    $vars['small_breakpoint'] = $global_settings->responsive_breakpoint . 'px';
  }
  else {
    $vars['medium_breakpoint'] = '1024px';
    $vars['small_breakpoint'] = '768px';
  }

  // Express font size relative the text size.
  $text_size = ((float) $vars['text-size']);
  $vars['root-size'] = ($text_size / 1.5) . 'px';
  $vars['h1-size'] = ((float) $vars['h1-size']) / $text_size . 'em';
  $vars['h2-size'] = ((float) $vars['h2-size']) / $text_size . 'em';
  $vars['h3-size'] = ((float) $vars['h3-size']) / $text_size . 'em';
  $vars['h4-size'] = ((float) $vars['h4-size']) / $text_size . 'em';
  $vars['h5-size'] = ((float) $vars['h5-size']) / $text_size . 'em';
  $vars['h6-size'] = ((float) $vars['h6-size']) / $text_size . 'em';

  return $vars;

});

// Create files that allows customization of the thee without conflict with
// this child theme.
add_action('after_switch_theme', function($name) {
  foreach (['css', 'js', 'php'] as $suffix) {
    $filename = FL_CHILD_THEME_DIR . '/custom/custom.' . $suffix;
    if (!file_exists($filename)) {
      file_put_contents($filename, '');
    }    
  }
});

// Load custom.css and custom.js
add_action('wp_enqueue_scripts', function () {
  wp_enqueue_script('kntnt-bb-child-theme-custom-js', FL_CHILD_THEME_URL .  '/custom/custom.js', ['jquery'], '1.0', true);
  wp_enqueue_style('kntnt-bb-child-theme-custom-css', FL_CHILD_THEME_URL . '/custom/custom.css', ['fl-automator-skin']);
}, 9999);

// Inlcude custom.php
file_exists(FL_CHILD_THEME_DIR .  '/custom/custom.php') && require_once FL_CHILD_THEME_DIR .  '/custom/custom.php';
